# Generated by Django 2.1 on 2018-08-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
