# Generated by Django 2.1 on 2018-08-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_stripe_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
