# Generated by Django 2.1 on 2018-08-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_canceled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='canceled_at',
        ),
    ]
