version: "3"
services:
  web:
    image: nginx
    container_name: nginx_server_platzi
    volumes:
      - ./djangoapp.template:/etc/nginx/conf.d/djangoapp.template
      - ./certs:/etc/nginx/certs
      - ./a.html:/var/www/html/index.html
    ports:
    - "80:80"
    - "443:443"
    links:
      - django
    environment:
    - NGINX_HOST=platzitest.dev
    - NGINX_PORT=80
    command : /bin/bash -c "envsubst < /etc/nginx/conf.d/djangoapp.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
  django:
    container_name: django_server_platzi
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/platzigram
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - db
    environment:
      - DATABASE_URL=mysql://root:123456@db:3306/platzi-test
    depends_on:
      - db
  db:
    container_name: mysql_django_platzi
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=laclave
      - MYSQL_ROOT_HOST=%