# Generated by Django 2.1 on 2018-08-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
