# Generated by Django 2.1 on 2018-08-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
    ]
