# Generated by Django 2.1 on 2018-08-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_is_annual'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
