# Generated by Django 2.1 on 2018-08-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_subscription_canceled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ends_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
